### PR TITLE
feat: add message model and the context processor DS-620

### PR DESCRIPTION
**Pull request by MaferMazu**
## Description

This PR adds:
- ValidationStatusMessage model
    - ValidationStatusMessageAdmin
    - Migration file
- Creates a context_processor (to send variables to the front)
    - Adds settings to add that context_processor
    - Creates a file utils to use in the context_processor
        - 2 backends to use in utils

📌 This PR will be used for: https://github.com/eduNEXT/ednx-saas-themes/pull/177

## How to test

1. Be able to create Status Messages from the Django Admin.
2. Be able to use the variables: course_status, status_message, and status_button on the templates.
    - Particularly in:
        - CMS Course Outline. e.g.  http://studio.local.overhang.io:8001/course/course-v1:edX+test+2023
        - CMS Course Unit. e.g. http://studio.local.overhang.io:8001/container/block-v1:edX+test+2023+type@vertical+block@0df8158f88374b03b12c45181726e64e

**Note:** To try the availability of the variables, you can add the following inside the body tag in edx-platform/cms/templates/base.html:
```
    <p>#######################</p>
    <h2>:D</h2>
    <p>${validation_panel_course_status or ''}</p>
    <p>${validation_panel_message or ''}</p>
    <p>${validation_panel_button or ''}</p>
```
(This example works if you have a validation process in the course page you are testing and you have a message for the status of that validation process.)
## Screenshots
Screenshot from 2023-09-19 23-23-21
Screenshot from 2023-09-19 22-50-29

### CODE REVIEW

**Comment by MaferMazu** [comment]
I want your feedback on all the PR but, I'm not so sure about the naming of the things, particularly the names of the variables to be used in the front end. Is it a good idea to add a prefix to the var names, or what do you think?

**Comment by dcoa** [comment]
Thanks @MaferMazu, yes I think is better if we add a prefix to indicate which app or feature is related something like `validation_panel_message` could work

**Comment by MaferMazu** [comment]
A new way to call the variables:
```
    <p>${validation_panel_course_status or ''}</p>
    <p>${validation_panel_message or ''}</p>
    <p>${validation_panel_button or ''}</p>
```

If you have more feedback, I'm attentive.

**Review by dcoa — APPROVED** [review]
this works as we expected to do it.

**Pull request merged**
