### PR TITLE
feat: added names on endpoints

### PR DESCRIPTION
**Pull request by Asespinel**
This PR adds the names required in the process validation endpoints.

How to Test

call the endpoint for exmaple: 
local.overhang.io:8000/plugin-cvw/api/v1/validation-processes/course-v1:test+CS101+2023_T1

As a response you should see the names as follows:

{
    "id": 2,
    "course": {
        "id": "course-v1:test+CS101+2023_T1",
        "display_name": "test"
    },
    "categories": [
        {
            "id": 1,
            "name": "courseCategory1",
            "parent_category": null
        }
    ],
    "organization": {
        "id": 2,
        "name": "test",
        "short_name": "test"
    },
    "current_validation_user": null,
    "validation_body": {
        "id": 1,
        "validators": [
            {
                "email": "admin@example.com"
            }
        ],
        "organizations": [
            {
                "id": 1,
                "name": "edX",
                "short_name": "edX"
            }
        ],
        "name": "validationBody1"
    },
    "events": [
        {
            "id": 2,
            "username": "admin",
            "create_at": "2023-09-15T17:56:17.948529Z",
            "status": "subm",
            "comment": "test comment",
            "validation_process": 2,
            "user": 4,
            "reason": null
        }
    ],
    "username": admin
}

### CODE REVIEW

**Comment by MaferMazu** [comment]
@Asespinel, please let's continue the conversation here if you have comments or actions in your PR about @bra-i-am feedback from #14. 🙌

**Comment by dcoa** [comment]
I will continue the conversation here:

> About the current_validation_user, you obtain an id. I suppose you need the username, right? cc @Asespinel

In this case, we prefer if you could send the user display_name, because this is a read field if you don't send it we have to make another request to the backend to obtain the value.

> About the validation body, you already have the info you need. I think it Is important to have enough information in the response, but if we really think the validators and the org of a validation body are unnecessary, I think we can remove it (cc @Asespinel we need to be sure that change this don't break the endpoints). I think it is nice to have it because maybe we don't need it in the front right now, but it could be helpful for other purposes. But I don't have a strong position on this.

I agree with your position

> About the user, you are right. I think @Asespinel resolved that in https://github.com/eduNEXT/platform-global-teacher-campus/pull/16, creating a username element.

This is the same case as current_validation_user.


thanks @MaferMazu

**Comment by Asespinel** [comment]
Hi there,

the username mentioned in the response is associated with the current validation user ID. If I understand correctly, you'd like to update the "username" property to "display_name." Is that correct? If not please specify the exact property that you need.

Please confirm, and we can proceed accordingly. @dcoa @bra-i-am

Regarding the removal of the extra data received from the endpoints, I think it's better to leave it as it is as the information might be useful in other applications.

**Comment by bra-i-am** [comment]
Hi Andrés, 

Just to confirm, when you say:
> The username mentioned in the response is associated with the current validation user ID. If I understand correctly, you'd like to update the "username" property to "display_name." Is that correct? If not please specify the exact property that you need.

There is something that is not that clear to me, you are going to change the property "username" by the "display_name" (**I agree with that because we need the name of the current validation user**), but will you delete the "current_validation_user" property or... what will happened with that? I just ask with curiosity because I see that 'username' is a separate property
 
 Additionally, in each event, **we need the display_name of the user too:**
 ```json
"events": [
    {
        "id": 2,
        "username": "admin",
        "create_at": "2023-09-15T17:56:17.948529Z",
        "status": "subm",
        "comment": "test comment",
        "validation_process": 2,
        "user": 4, // Instead of this number, we need the display_name
        "reason": null
    }
]
  ```
  
  
And yes, you're right about this!!
> Regarding the removal of the extra data received from the endpoints, I think it's better to leave it as it is as the information might be useful in other applications.

**Comment by Asespinel** [comment]
Thank you for the quick answer brayan. As for the "current_validation_user" property, I will not delete it but I was thinking of adding extra data as follows:
```json
"current_validation_user": {
        "id": 4,
        "email": "admin@example.com",
        "username": "admin"
    },
```
The email is there to not modify much of the actual code. The separate "username" property would be turned into the "display_name" property  and it would be effectivly the same user related to the current_validation_user. 

On the other hand, the username inside "events" would work for you? Or do you need me to change it to display_name? Let me know if you need more info or ahve any more questions.

**Comment by Asespinel** [comment]
After doing some tests I discovered a bug in the validation process serializer which caused a type error to be returned. I tested the endpoint again and it shows no errors with the new information added as requested. I added some extra information that it might prove useful. The property "full_name" was added in the User Serializer to show a combination of the "Name+LasName" of every user. An example of the full data returned:

```json
{
    "id": 2,
    "course": {
        "id": "course-v1:test+CS101+2023_T1",
        "display_name": "test"
    },
    "categories": [
        {
            "id": 1,
            "name": "courseCategory1",
            "parent_category": null
        }
    ],
    "organization": {
        "id": 2,
        "name": "test",
        "short_name": "test"
    },
    "current_validation_user": {
        "id": 4,
        "email": "admin@example.com",
        "username": "admin",
        "full_name": "Andres Espinel"
    },
    "validation_body": {
        "id": 1,
        "validators": [
            {
                "id": 4,
                "email": "admin@example.com",
                "username": "admin",
                "full_name": "Andres Espinel"
            }
        ],
        "organizations": [
            {
                "id": 1,
                "name": "edX",
                "short_name": "edX"
            }
        ],
        "name": "validationBody1"
    },
    "events": [
        {
            "id": 2,
            "user": {
                "id": 4,
                "email": "admin@example.com",
                "username": "admin",
                "full_name": "Andres Espinel"
            },
            "username": "admin",
            "create_at": "2023-09-15T17:56:17.948529Z",
            "status": "subm",
            "comment": "test comment",
            "validation_process": 2,
            "reason": null
        }
    ]
}

Please let me know If you need anything else to be returned.

```

**Comment by dcoa** [comment]
@Asespinel thank you that should be enough by now in terms of the information that we need.

**Review by bra-i-am — APPROVED** [review]
Looks pretty good to me, thanks a lot @Asespinel

**Review by MaferMazu — APPROVED** [review]

**Comment by MaferMazu** [comment]
Thanks for this @Asespinel

**Pull request merged**
